services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    # 2. Keep alive the container in second plane
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"